"""
generate_ui.py — PlatformIO pre-build script
Reads src/index.html, gzip-compresses it, and writes src/ui.h containing
the compressed bytes as a PROGMEM array. main.cpp serves it with
Content-Encoding: gzip so the browser decompresses transparently.

Run automatically before every build via platformio.ini:
    extra_scripts = pre:generate_ui.py
"""

import os
import gzip

Import("env")  # noqa: F821 — injected by PlatformIO

SRC_HTML = os.path.join(env["PROJECT_DIR"], "src", "index.html")  # noqa: F821
OUT_H    = os.path.join(env["PROJECT_DIR"], "src", "ui.h")        # noqa: F821


def generate_ui_header(source, target, env):  # noqa: F811
    print("Generating src/ui.h from src/index.html (gzip compressed)...")

    with open(SRC_HTML, "rb") as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)

    # Format as a C byte array, 16 bytes per line
    lines = []
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i+16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk))
    array_body = ",\n".join(lines)

    out = (
        "// AUTO-GENERATED — do not edit directly.\n"
        "// Edit src/index.html and rebuild.\n"
        "// Generated by generate_ui.py: gzip-compressed HTML for PROGMEM.\n"
        "#pragma once\n"
        "\n"
        f"// Original: {len(raw):,} bytes  Compressed: {len(compressed):,} bytes"
        f"  ({100*(1-len(compressed)/len(raw)):.0f}% reduction)\n"
        f"const uint32_t INDEX_HTML_LEN = {len(compressed)};\n"
        f"const uint8_t  INDEX_HTML[] PROGMEM = {{\n"
        f"  {array_body}\n"
        f"}};\n"
    )

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"  {len(raw):,} bytes → {len(compressed):,} bytes "
          f"({100*(1-len(compressed)/len(raw)):.0f}% reduction) → src/ui.h")


# Run before source compilation so ui.h exists when main.cpp is compiled
env.AddPreAction("$BUILD_DIR/src/main.cpp.o", generate_ui_header)
