; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-atom]
;platform = espressif32
platform = espressif32 @ 6.11.0
board = m5stack-atom
framework = arduino
monitor_port = /dev/cu.usbserial-9D5EF3DB00

monitor_speed = 115200
lib_deps = 
	ttlappalainen/NMEA2000-library@^4.22.1
	ttlappalainen/NMEA2000_esp32@^1.0.3
	m5stack/M5Atom@^0.1.3
	fastled/FastLED@^3.10.2
